spring:
   security:
      oauth2:
         client:
            registration:
               github:
                  clientId: ${GITHUB_CLIENT_ID}
                  clientSecret: ${GITHUB_CLIENT_SECRET}
               google:
				  client-id: ${GOOGLE_CLIENT_ID}
				  client-secret: ${GOOGLE_CLIENT_SECRET}
#                  redirect-uri: http://localhost:4200/oauth2/redirect

app:
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
      - http://localhost:4200/oauth2/redirect
      - http://localhost:4200/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
